version: '3.8'

services:
  pilgrim:
    image: registry.bhyoo.com/pilgrim
    networks:
      - traefik-public
    volumes:
      - /mnt/pilgrim:/var/lib/pilgrim
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      mode: replicated
      replicas: 2
      labels:
        - traefik.enable=true
        - traefik.http.routers.pilgrim-insecure.rule=Host(`pilgrim.${DOMAIN?Variable not set}`)
        - traefik.http.routers.pilgrim-insecure.entrypoints=web
        - traefik.http.routers.pilgrim-insecure.middlewares=redirectscheme
        - traefik.http.routers.pilgrim.rule=Host(`pilgrim.${DOMAIN?Variable not set}`)
        - traefik.http.routers.pilgrim.tls=true
        - traefik.http.routers.pilgrim.entrypoints=web-secure
        - traefik.http.services.pilgrim.loadbalancer.server.port=80

networks:
  traefik-public:
    external: true
