version: '3.8'

services:
  registry:
    image: registry:2.7
    networks:
      - traefik-public
    volumes:
      - /mnt/registry:/var/lib/registry
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.registry-insecure.rule=Host(`registry.${DOMAIN?Variable not set}`)
        - traefik.http.routers.registry-insecure.entrypoints=web
        - traefik.http.routers.registry-insecure.middlewares=redirectscheme
        - traefik.http.routers.registry.rule=Host(`registry.${DOMAIN?Variable not set}`)
        - traefik.http.routers.registry.entrypoints=web-secure
        - traefik.http.routers.registry.tls=true
        - traefik.http.services.registry.loadbalancer.server.port=5000

networks:
  traefik-public:
    external: true
