version: '3.9'

services:
  reverse-proxy:
    ports:
      - published: 80
        target: 80
        mode: host
      - published: 443
        target: 443
        mode: host
    image: traefik:2.4
    networks:
      - traefik-public
      - datadog
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
      mode: global
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=true
        - traefik.http.routers.reverse-proxy-insecure.rule=Host(`traefik.${DOMAIN?Variable not set}`)
        - traefik.http.routers.reverse-proxy-insecure.entrypoints=web
        - traefik.http.routers.reverse-proxy-insecure.middlewares=redirectscheme
        - traefik.http.routers.reverse-proxy.rule=Host(`traefik.${DOMAIN?Variable not set}`)
        - traefik.http.routers.reverse-proxy.entrypoints=web-secure
        - traefik.http.routers.reverse-proxy.tls=true
        - traefik.http.routers.reverse-proxy.service=api@internal
        - traefik.http.routers.reverse-proxy.middlewares=admin-auth
        - traefik.http.middlewares.admin-auth.basicauth.users=${USERNAME?Variable not set}:${HASHED_PASSWORD?Variable not set}
        - traefik.http.middlewares.redirectscheme.redirectscheme.scheme=https
        - traefik.http.middlewares.redirectscheme.redirectscheme.permanent=true
        - traefik.http.services.reverse-proxy.loadbalancer.server.port=8080
    command:
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik-public
      - --providers.file.filename=/run/secrets/traefik_tls_conf.yml
      - --entryPoints.web.address=:80
      - --entryPoints.web.forwardedHeaders.trustedIPs=127.0.0.1/32,10.0.0.1/24
      - --entryPoints.web-secure.address=:443
      - --entryPoints.web-secure.forwardedHeaders.trustedIPs=127.0.0.1/32,10.0.0.1/24
      - --accesslog=true
      - --accesslog.format=json
      - --accesslog.fields.headers.defaultmode=keep
      - --metrics.datadog=true
      - --metrics.datadog.address=datadog_agent:8125
      - --tracing.datadog=true
      - --tracing.datadog.localAgentHostPort=datadog_agent:8126
      - --log.format=json
      - --api
    secrets:
      - web_certificate
      - web_private_key
      - traefik_tls_conf.yml

secrets:
  web_certificate:
    file: cert/${DOMAIN?Variable not set}.pem
  web_private_key:
    file: cert/${DOMAIN?Variable not set}.key
  traefik_tls_conf.yml:
    file: cert/traefik_tls_conf.yml

networks:
  traefik-public:
    external: true
  datadog:
    external: true
